### ISSUE TITLE
ANRs at App Start with very high frequency on Android 8 (but also newer OS versions) - (v6.11.1)

### ISSUE THREAD

**Issue by marxhendrik** [AppsFlyerSDK/appsflyer-android-sdk#57]
We noticed a sharp increase in a native Crash on Android 8 a while ago. We could not precisely determine which change was causing the crash because of native stack traces. We saw that one of our changes in the offending release was bumping the appsflyer version to v6.10.3. We bumped the release to 6.11.1 with the subsequent release but the issue did not stop. However now we also see the same issue for newer devices than Android 8 and have stacktraces with appsflyer as root in the Stacktrace:

On newer devices (around 50 occurences in the last week)
```
main (runnable):tid=1 systid=14009 
#00 pc 0x6aafa8 libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool) + 128) (BuildId: 4c9b59b74ca9272f710a71137164c349)
#01 pc 0x713144 libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const + 236) (BuildId: 4c9b59b74ca9272f710a71137164c349)
#02 pc 0x722390 libart.so (art::DumpCheckpoint::Run(art::Thread*) + 208) (BuildId: 4c9b59b74ca9272f710a71137164c349)
#03 pc 0x425444 libart.so (art::Thread::RunCheckpointFunction() + 140) (BuildId: 4c9b59b74ca9272f710a71137164c349)
#04 pc 0x403c5c libart.so (art::verifier::impl::(anonymous namespace)::MethodVerifier<false>::VerifyCodeFlow() (.__uniq.63246233319839034720636906213703941800.llvm.15746418181848386190) + 4580) (BuildId: 4c9b59b74ca9272f710a71137164c349)
#05 pc 0x3fd3a8 libart.so (art::verifier::MethodVerifier::FailureData art::verifier::MethodVerifier::VerifyMethod<false>(art::Thread*, art::ClassLinker*, art::ArenaPool*, art::verifier::VerifierDeps*, unsigned int, art::DexFile const*, art::Handle<art::mirror::DexCache>, art::Handle<art::mirror::ClassLoader>, art::dex::ClassDef const&, art::dex::CodeItem const*, unsigned int, art::verifier::HardFailLogMode, unsigned int, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) + 2020) (BuildId: 4c9b59b74ca9272f710a71137164c349)
#06 pc 0x3fbc10 libart.so (art::verifier::ClassVerifier::VerifyClass(art::Thread*, art::verifier::VerifierDeps*, art::DexFile const*, art::Handle<art::mirror::Class>, art::Handle<art::mirror::DexCache>, art::Handle<art::mirror::ClassLoader>, art::dex::ClassDef const&, art::CompilerCallbacks*, art::verifier::HardFailLogMode, unsigned int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) + 1092) (BuildId: 4c9b59b74ca9272f710a71137164c349)
#07 pc 0x3fb750 libart.so (art::ClassLinker::PerformClassVerification(art::Thread*, art::verifier::VerifierDeps*, art::Handle<art::mirror::Class>, art::verifier::HardFailLogMode, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) + 304) (BuildId: 4c9b59b74ca9272f710a71137164c349)
#08 pc 0x3c1518 libart.so (art::ClassLinker::VerifyClass(art::Thread*, art::verifier::VerifierDeps*, art::Handle<art::mirror::Class>, art::verifier::HardFailLogMode) + 3016) (BuildId: 4c9b59b74ca9272f710a71137164c349)
#09 pc 0x43f19c libart.so (art::ClassLinker::InitializeClass(art::Thread*, art::Handle<art::mirror::Class>, bool, bool) + 788) (BuildId: 4c9b59b74ca9272f710a71137164c349)
#10 pc 0x61df1c libart.so (art::Constructor_newInstance0(_JNIEnv*, _jobject*, _jobjectArray*) (.__uniq.114100828369361150012403296395805223021) + 272) (BuildId: 4c9b59b74ca9272f710a71137164c349)
       at java.lang.reflect.Constructor.newInstance0(Native method)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at com.appsflyer.internal.AFa1wSDK.<clinit>(:2547)
       at com.appsflyer.internal.AFa1dSDK.values(:50177)
       at com.appsflyer.internal.AFa1dSDK.<clinit>(:142)
       at com.appsflyer.internal.AFa1dSDK.valueOf(:242)
       at com.appsflyer.AppsFlyerLib.getInstance(:24)
``` 

This is the same crash for Android 8 devices (we have more than 7000 occurrences of this crash in the last 7 days!).
The stacktrace probably does not help much. libhwui.so indicates an ANR though and the occurences of this crash coincides with our update to version v6.10.3.
```
Crashed: Thread: SIGABRT  0x0000000000000000
#00 pc 0x1a7ae libc.so (BuildId: 027d9e79b7ca6bf6aa2abfa5b629dcfd)
#01 pc 0x2cd4e libhwui.so (BuildId: f4c6104738f48217f841ec3e1862b442)
#02 pc 0x2cd4e libhwui.so (BuildId: f4c6104738f48217f841ec3e1862b442)
#03 pc 0x2cd4e libhwui.so (BuildId: f4c6104738f48217f841ec3e1862b442)
...
``` 

It would be very helpful to address this issue. I assume that this is flying under the radar for some other projects because most occurences are on Android 8 with a stracktrace that does not mention appsflyer.

**Comment by marxhendrik** [comment]
We are still in partial rollout,but it looks like the crashes are fixed with 6.12

**Comment by dogtim** [comment]
We upgraded to 6.12.1 but still have the crash report on Android 8.
```
Caused by java.lang.IllegalAccessException: Class java.lang.Class<java.lang.reflect.Method> cannot access protected  method java.lang.Class com.appsflyer.internal.AFb1mSDK$$.loadClass(java.lang.String, boolean) of class java.lang.Class<com.appsflyer.internal.AFb1mSDK$$>
       at java.lang.reflect.Method.invokeImpl(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:411)
       at com.appsflyer.internal.AFb1mSDK$$.AFKeystoreWrapper(:100)
       at com.appsflyer.internal.AFb1mSDK$$.values(:19)
       at java.lang.reflect.Method.invokeImpl(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:411)
       at com.appsflyer.internal.AFb1pSDK.values(:125)
       at com.appsflyer.internal.AFd1eSDK.values(:9132)
       at com.appsflyer.internal.AFd1eSDK.AFKeystoreWrapper(:78)
       at com.appsflyer.internal.AFd1nSDK.AFInAppEventParameterName(:115)
       at com.appsflyer.internal.AFd1tSDK$5.run(:109)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by ge-af** [comment]
Hi, 
We've just released a new Android SDK version that fixes this issue.
The new version is v6.12.2.
